version: '3'
services:
    contneo4j410:
        image: rbewoor/myneo4j410nocmd:1.0
        environment:
            - NEO4J_AUTH=neo4j/cba
        healthcheck:
            test: wget http://localhost:7474 || exit 1
            interval: 1s
            timeout: 10s
            retries: 20
            start_period: 10s
        ports:
            - "27474:7474"
        volumes:
            - ./tempneo4j/data:/var/lib/neo4j/data:rw
#        networks:
#            - mywineappnetwork
    contwinereviewapp:
        image: rbewoor/winereviewapp:1.0
        depends_on:
            contneo4j410:
                condition: service_healthy
#        networks:
#            - mywineappnetwork
#        links:#deprecated and they docker docs say to use networks and volumes
#            - contneo4j410
        environment:
            - NEO4J_CONTAINER_NAME=contneo4j410
            - DISPLAY=$DISPLAY
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
#networks:
#    mywineappnetwork:
#        driver: bridge